{pkgs}: {
  deps = [
    pkgs.gdb
    pkgs.htop
    pkgs.diesel-cli-ext
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.vim
    pkgs.trunk
    pkgs.wasm-pack
    pkgs.just
    pkgs.pandoc
    pkgs.tig
    pkgs.diesel-cli
    pkgs.openssl
    pkgs.pkg-config
    pkgs.tmux
    pkgs.sqlite
  ];
}
